name: Eperusteet-backend-utils build
on:
#  release:
#    types: [ created ]
  push:
    branches: [ master, github-packages-actions ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          server-id: github
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to Github
        run: mvn deploy --batch-mode --projects .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Artifactory
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
<<<<<<< HEAD
          mvn deploy --batch-mode --projects . --settings ci-tools/common/maven-settings.xml
=======
          mvn deploy --batch-mode --projects . --settings ci-tools/common/maven-settings.xml -DaltDeploymentRepository=oph-sade-artifactory::default::https://artifactory.opintopolku.fi/artifactory/oph-sade-release-local -DaltSnapshotDeploymentRepository=oph-sade-artifactory::default::https://artifactory.opintopolku.fi/artifactory/oph-sade-snapshot-local -DuniqueVersion=false
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
>>>>>>> de18777 (unique version fix)
