name: Eperusteet-backend-utils build
on: [workflow_dispatch, push]

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
          server-id: github
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to Github
        run: mvn deploy --batch-mode --projects .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Artifactory
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          mvn deploy -B --settings ci-tools/common/maven-settings.xml
