name: Eperusteet-backend-utils build
on: [workflow_dispatch, push]

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Package
        run: mvn clean package

      - name: Publish snapshot
        if: ${{ success() && github.ref_name != 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy --batch-mode -DskipTests
      - name: Release
        if: ${{ success() && github.ref_name == 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          mvn release:clean release:prepare release:perform -DignoreSnapshots=true
         
# mvn build-helper:parse-version versions:set -DnewVersion=${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion} versions:commit
