name: Eperusteet-backend-utils build
on: [workflow_dispatch, push]

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Publish snapshot
        if: ${{ success() && github.ref_name != 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy --batch-mode -DskipTests
      - name: Deploy
        if: ${{ success() && github.ref_name == 'master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn release:clean release:prepare release:perform -DignoreSnapshots=true
